algodex/algodex-sdk

- README.md
> 🔗Updated links to public endpoint in Readme

- lib/order/http/AlgodexClient.js
- lib/order/structure/getTakerOrders.js
- package.json
> Issue 191 🐛 fix asset decimals

- lib/utils/groupBy.js
- lib/wallet/signers/MyAlgoConnect.js
- lib/wallet/signers/WalletConnect.js
Added signing methodology for Wallet-connect
> Issue 198 ✨ feature wallet connect signing

- lib/AlgodexApi.js
- lib/http/clients/IndexerClient.js
- lib/http/clients/IndexerClient.spec.js
- lib/schema.js
- lib/schema.spec.js
- package.json
- spec/Config.js
Changed AJV schema, setConfig(), and HTTP/IndexerClient to account for instances of `algosdk.Algodv2` and `algosdk.Indexer`
> Issue 189 ✨ feature allow algodv2 and indexer instances

- lib/AlgodexApi.js
> Fix OR symbols to coalesce first non-null in indexer

- lib/AlgodexApi.js
- lib/http/clients/IndexerClient.js
- lib/http/clients/IndexerClient.spec.js
- lib/order/structure/taker/getCutTakerOrders.js
- lib/order/txns/buy/makePlaceAlgoTxns.js
- lib/schema.js
- lib/schema.spec.js
- lib/utils/groupBy.js
- lib/wallet/getMinBalance.js
- lib/wallet/signers/MyAlgoConnect.js
- lib/wallet/signers/WalletConnect.js
- package.json
- spec/Config.js
Changes to be included in 📦 v2.0.2
> Development 

- lib/order/__tests__/GenerateTransactionTypes.js
- lib/order/__tests__/TealAsaEscrowPlace.spec.js
- lib/order/__tests__/asa_dex_teal.js
- lib/order/__tests__/beforeAll.js
- lib/order/__tests__/constants.js
- lib/order/__tests__/dex_teal.js
- lib/order/__tests__/generate_transaction_types.js
- lib/order/__tests__/setup.js
- lib/order/__tests__/teal_tests/createAppTest.js
- lib/order/__tests__/teal_tests/placeASAEscrowOrder.js
- lib/order/txns/buy/makeExecuteAlgoTxns.spec.js
- lib/teal/test/initAccounts.js
- lib/teal/utils.js
> 226 acceptance add tests for all the different order types

- lib/order/__tests__/GenerateTransactionTypes.js
- lib/order/__tests__/Teal.spec.js
- lib/order/__tests__/TealAlgoEscrowPlaceWithOptInTxn.spec.js
- lib/order/__tests__/TealAsaEscrowPlace.spec.js
- lib/order/__tests__/TealConfig.js
- lib/order/__tests__/accountSetup.js
- lib/order/__tests__/teal_tests/placeASAEscrowOrder.js
- lib/order/__tests__/teal_tests/placeAlgoEscrowOrder.js
- lib/order/__tests__/teal_tests/sendTransactions.js
- lib/teal/test/initAccounts.js
> ✨ Test passing for placeAlgoWithOptIn using v2

- lib/order/__tests__/TealAlgoEscrowPlaceNoOptInTxn.spec.js
- lib/order/__tests__/TealAlgoEscrowPlaceWithOptInTxn.spec.js
- lib/teal/test/initAccounts.js
- lib/teal/utils.js
> 236 teal algo escrow place no opt in txn

- lib/order/__tests__/GenerateTransactionTypes.js
- lib/order/__tests__/TealAlgoEscrowPlaceNoOptInTxn.spec.js
- lib/order/__tests__/TealAlgoEscrowPlaceWithOptInTxn.spec.js
- lib/order/__tests__/TealAsaEscrowCancel.spec.js
- lib/order/__tests__/initCloseOrderAccounts.js
- lib/order/__tests__/teal_tests/closeASAEscrowOrder.js
- lib/teal/test/initAccounts.js
> ✨Cancel ASA set up and test complete

- lib/order/__tests__/TealAsaEscrowPlace.spec.js
- lib/order/__tests__/accountCleanup.js
Teal ASA Escrow Place is completed for Positive test case using v2, including full cancellation and account clean up
> ✨ Closing Order and cleanupStep for TealAsaEscrowPlace

- lib/order/__tests__/TealAsaEscrowPayPartialNoOptInTxn.spec.js
- lib/order/__tests__/takerAccountCleanup.js
> ✨Cleanup step for partial execution no optin

- lib/AlgodexApi.js
- lib/order/structure/getMakerTakerOrders.js
- lib/order/structure/taker/getCutTakerOrders.js
- lib/order/txns/sell/makeExecuteAssetTxns.js
Improved the transaction speed by synchronously mapping and sending the transaction group and then awaiting the resolution of them all as opposed to sending and awaiting in sequence. 
NOTE: The only relevant file is the changes in `AlgodexApi.js`. All the other file changes are represented in #255
> Issue 250 ✅ acceptance improve the speed of sending transactions

- lib/AlgodexApi.js
- package.json
📦 Patch point and adding back new signing functionality that was approved but got overwritten
> Issue 254 fix taker execution with closeout across multi orders not behaving as expected

- lib/AlgodexApi.js
- lib/order/txns/sell/makeExecuteAssetTxns.js
> 260 acceptance change the  sendtransaction function to batch await txid confirmations but sequentially send txn groups

- lib/AlgodexApi.js
- lib/utils/errorParser.js
Added a util for parsing error messages and finding edgecases 
Added a tryCatch to `_sendTransactions()` which will now only throw if an edgecase is not detected. 
#267
> Issue 267 acceptance wrap the sending of a raw transaction in try catch statement for better error handling

- lib/AlgodexApi.js
- package.json
Reverted the try-catch in the sending function to match v1 implementation 
#272
> Issue 272 acceptance revert send transactions to not throw any errors to the front end

- lib/order/__tests__/TealAlgoEscrowPayPartial.spec.js
- lib/order/__tests__/teal_tests/executeAlgoEscrowOrder.js
- lib/order/__tests__/teal_tests/sendTransactions.js
Added positive test for Algo Partial pay (Algo Taker)
#275
> 275 teal algo partial pay no opt in

- lib/order/__tests__/TealAlgoEscrowPayCloseout.spec.js
- lib/order/__tests__/TealAlgoEscrowPayPartial.spec.js
- lib/order/__tests__/takerAccountCleanup.js
Added clean up for partial and closeout Algo orders and built out the positive v2 test for algo pay with closeout.
#277
> 277 teal algo pay with closeout

- lib/AlgodexApi.js
- package.json
> Add purestake support

- lib/order/__tests__/TealAsaEscrowPayCloseoutNoOptInTxn.spec.js
Tests passing as expected
#286
> ✅ Passing test for TealAsaEscrowPayCloseoutNoOptInTxn

- lib/order/__tests__/TealAlgoEscrowCancel.spec.js
- lib/order/__tests__/TealAsaEscrowCancel.spec.js
- lib/order/__tests__/initCloseOrderAccounts.js
Passing tests for canceling an algo escrow order.  This marks the completion of the positive tests. 
#288
> 288 teal algo escrow cancel

- lib/order/__tests__/TealAlgoEscrowCancel.spec.js
- lib/order/__tests__/TealAlgoEscrowPayCloseout.spec.js
- lib/order/__tests__/TealAlgoEscrowPayPartial.spec.js
- lib/order/__tests__/TealAlgoEscrowPlaceNoOptInTxn.spec.js
- lib/order/__tests__/TealAlgoEscrowPlaceWithOptInTxn.spec.js
- lib/order/__tests__/TealAsaEscrowCancel.spec.js
- lib/order/__tests__/TealAsaEscrowPayCloseoutNoOptInTxn.spec.js
- lib/order/__tests__/TealAsaEscrowPayCloseoutWithOptInTxn.spec.js
- lib/order/__tests__/TealAsaEscrowPayPartialNoOptInTxn.spec.js
- lib/order/__tests__/TealAsaEscrowPayPartialWithOptInTxn.spec.js
- lib/order/__tests__/TealAsaEscrowPlace.spec.js
- lib/order/__tests__/teal_tests/executeASAEscrowOrder.js
- lib/order/__tests__/teal_tests/executeAlgoEscrowOrder.js
- lib/order/__tests__/teal_tests/placeAlgoEscrowOrder.js
Naming fixes and general organizational cleanup
#292
> 292 improve documentation and standardize naming across different tests

- lib/order/structure/getTakerOrders.js
> 🐞 Changed the void return to an array

- LICENSE.md
> update license to show full text

- lib/order/http/AlgodexClient.js
This a fix for a problem Minh noticed with the links in the trade history. This change to the SDK should make it so the front end has to change nothing, it will just work with the new patch point.
#312
> 🐞Added groupId property to the response of the mapping

- lib/wallet/getWalletAssetAmount.js
- package.json
> Fix issue when wallet has no assets

- lib/AlgodexApi.js
- lib/http/HTTPClient.js
- lib/order/http/AlgodexClient.js
- package-lock.json
- package.json
> switch to new API

- lib/order/http/AlgodexClient.js
- package.json
> Add support for more 2.0 APIs

- lib/order/http/AlgodexClient.js
- package.json
> change urls for search
